CREATE TABLE IF NOT EXISTS cars (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    price DECIMAL(10,2),
    mileage INT,
    year YEAR,
    link TEXT,
    scraped_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);